{% set name = "llama-index-embeddings-openai" %}
{% set version = "0.6.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
    sha256: eb3e6606be81cb89125073e23c97c0a6119dabb4827adbd14697c2029ad73f29
  # https://github.com/run-llama/llama_index/issues/10806
  - url: https://raw.githubusercontent.com/run-llama/llama_index/main/LICENSE
    sha256: 24f40b5190fdacabc24ddbb5f76364d15e4f030925220ea300d8a2dd4993c8cb

build:
  number: 0
  # llama-index-core doesn't support Python 3.14+ because of dataclasses-json, which is unmaintainable anymore,
  # and does not support Python 3.14+ as well (https://github.com/lidatong/dataclasses-json/issues/568)
  skip: true # [py<310 or py>313]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - openai >=1.1.0
    - llama-index-core >=0.13.0,<0.15

test:
  imports:
    - llama_index.embeddings.openai
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.llamaindex.ai
  summary: llama-index embeddings openai integration
  description: |
    LlamaIndex embeddings integration with OpenAI. Provides the OpenAIEmbedding
    class for generating text embeddings using OpenAI models such as
    text-embedding-3-large and text-embedding-3-small.
  license: MIT
  license_file: LICENSE
  license_family: MIT
  doc_url: https://developers.llamaindex.ai/python/framework/integrations/embeddings/openai/
  dev_url: https://github.com/run-llama/llama_index/tree/main/llama-index-integrations/embeddings/llama-index-embeddings-openai

extra:
  recipe-maintainers:
    - jan-janssen
    - pavelzw
